### ISSUE TITLE
switch to Test::Exception

### ISSUE THREAD

**Issue by karenetheridge** [sekia/Algorithm-LossyCount#1]
The time where Test:Exception::LessClever was useful has passed; it's time to go back to Test::Exception or use Test::Fatal.

**Comment by sekia** [comment]
Is there any positive motivation?
At least T::E::LessClever does the work I expected and has less dependencies than Test::Exception.
Test::Fatal certainly seems to have nice API and a few dependencies (thanks for informing. I never used the module) but requires test rewriting.

**Comment by sekia** [comment]
When some other changes are necessary for the module I'll update the test to use Test::Fatal, but it's not now.
